### ISSUE TITLE
Make the /claim command  trigger the claim() Solidity function

### ISSUE THREAD

**Issue by julienbrg** [AllForClimate/concord#36]
instead of updating the enmap db

**Comment by alexfurnica** [comment]
Instead of updating the enmap DB or also updating the enmap DB for now? I would keep enmap as well for now and later perhaps use a subgraph to keep records of all contract interactions. What do you think?

**Comment by julienbrg** [comment]
> Instead of updating the enmap DB or also updating the enmap DB for now? I would keep enmap as well for now 

Yes you're right, let's keep both. 

> and later perhaps use a subgraph to keep records of all contract interactions.

Yes, absolutely.
